#!/bin/bash -

## Password checker
## Checks a list of passwords against the hashes of known pwned passwords
## Hashes sourced from haveibeenpwned.com
## Reference: https://haveibeenpwned.com/API/v3#SearchingPwnedPasswordsByRange

API=https://api.pwnedpasswords.com/range/

listfile=$1

while IFS= read -r passwd; do 
  ##echo $passwd
  sha=`echo -n "${passwd}" | sha1sum | cut -f1 -d' ' | tr [:lower:] [:upper:]`
  #echo $sha
  sha_prefix=${sha:0:5}
  sha_suffix=${sha:5:35} 
  ## Get a range of suffixes that match the prefix, then look for ours
  match=`curl -s ${API}${sha_prefix} | grep ${sha_suffix}` >/dev/null
  matched=$?
  if [ $matched -eq 0 ]; then
    echo "Found pwned password: "${passwd} ${match}	   
  fi
done < $listfile

 
  
